
on: [push]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: msbuild
      uses: microsoft/setup-msbuild@v1.0.0

    - name: checkout 
      uses: actions/checkout@master 

    - name: compile 
      run:  msbuild travellingDistance.sln "/t:Clean,Rebuild" "/p:Configuration=Debug" "/p:Platform=x64"

