
on: [push]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: msbuild setup
      uses: microsoft/setup-msbuild@v1.0.0

    - name: vstest setup
      uses: darenm/Setup-VSTest@v1

    - name: checkout 
      uses: actions/checkout@master 

    - name: env
      run:  get-childitem ENV:

    - name: compile 
      run:  msbuild travellingDistance.sln /t:Clean,Rebuild /p:Configuration=Debug /p:Platform=x64

    - name: test 
      run:  vstest.console.exe bin\travellingDistance.dll /Platform:x64 /Logger:trx

